config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/history'

  get 'pages/how'

  get 'pages/terms'

resources :manufacturers, :cars, :bikes, :modells, :bodies, :engines, :fuels, :fuel_efficiencies, :speeds, :prices
  root "pages#home"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord

  belongs_to :manufacturer
  belongs_to :body
  belongs_to :modell
  belongs_to :engine
  belongs_to :fuel

end

app/models/body.rb
class Body < ApplicationRecord

  has_one :car
  has_one :bike
end

app/models/car.rb
class Car < ApplicationRecord

  belongs_to :manufacturer
  belongs_to :modell
  belongs_to :body
  belongs_to :engine
  belongs_to :fuel
  belongs_to :fuel_efficiency
  belongs_to :speed

end

app/models/engine.rb
class Engine < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/fuel.rb
class Fuel < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/fuel_efficiency.rb
class FuelEfficiency < ApplicationRecord

  has_one :car
  has_one :bike

end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord

  has_many :cars
  has_many :bikes
  has_many :modells
  has_many :bodies

end

app/models/modell.rb
class Modell < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/price.rb
class Price < ApplicationRecord

  has_one :bike
  has_one :car

end

app/models/speed.rb
class Speed < ApplicationRecord

    has_one :bike
    has_one :car

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_action :authenticate_user!

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController

  before_action :find_bodies, only:[:show, :edit, :update, :destroy]

  def index
    @bodies = Body.all.order("name ASC")
  end

  def new
    @body = Body.new
  end

  def create
    @body = Body.new(body_params)
      if @body.save
        redirect_to root_path
      else
        render 'new'
    end
  end

  def show

  end

  def edit

  end

  def update
    if @body.update(body_params)
      redirect_to body_path(@body)
    else
      render 'edit'
    end
  end

  def destroy
    @body.destroy
      redirect_to root_path
  end

  private

  def body_params
    params.require(:body).permit(:name, :description, :date, :meta_title, :meta_description, :permalink, :no_index)
  end

  def find_bodies
    @body = Body.find(params[:id])
  end

end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/modells_helper.rb
module ModellsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/speeds_helper.rb
module SpeedsHelper
end

app/views/bodies/_form.html.erb
<h1>Form Body Page</h1>

<%= simple_form_for @body, :html => { :multipart => true } do |f| %></br></br>

  <%= f.input :name %></br></br>

  <%= f.input :description, as: :text %></br></br>

  <%= f.input :no_index, as: :boolean, checked_value: true, unchecked_value: false %></br></br>

  <%= f.button :submit %></br></br>

<% end %>

<%= link_to "Back", root_path %>

app/views/bodies/edit.html.erb
<h1>Edit Body Page</h1>

<%= render 'form' %>

app/views/bodies/index.html.erb
<h1>Index Body Page</h1>

<% @bodies.each do |body| %>
<h2><%= link_to body.name, body_path(body) %></h2>
<% end %>

<%= link_to "Back", root_path %>

app/views/bodies/new.html.erb
<h1>New Body Page</h1>

<%= render 'form' %>

app/views/bodies/show.html.erb
<h1>Show Body Page</h1>

<h4><%= @body.name %></h4>
<h4><%= @body.description %></h4>
<h4><%= @body.date %></h4>

<%= link_to "Back", bodies_path %>
<%= link_to "Edit", edit_body_path(@body) %>
<%= link_to "Delete", body_path(@body), method: :delete, data:{confirm: "Are you sure?"} %>