config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/history'

  get 'pages/how'

  get 'pages/terms'

resources :manufacturers, :cars, :bikes, :modells, :bodies, :engines, :fuels, :fuel_efficiencies, :speeds, :prices
  root "pages#home"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord

  belongs_to :manufacturer
  belongs_to :body
  belongs_to :modell
  belongs_to :engine
  belongs_to :fuel

end

app/models/body.rb
class Body < ApplicationRecord

  has_one :car
  has_one :bike
end

app/models/car.rb
class Car < ApplicationRecord

  belongs_to :manufacturer
  belongs_to :modell
  belongs_to :body
  belongs_to :engine
  belongs_to :fuel
  belongs_to :fuel_efficiency
  belongs_to :speed

end

app/models/engine.rb
class Engine < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/fuel.rb
class Fuel < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/fuel_efficiency.rb
class FuelEfficiency < ApplicationRecord

  has_one :car
  has_one :bike

end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord

  has_many :cars
  has_many :bikes
  has_many :modells
  has_many :bodies

end

app/models/modell.rb
class Modell < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/price.rb
class Price < ApplicationRecord

  has_one :bike
  has_one :car

end

app/models/speed.rb
class Speed < ApplicationRecord

    has_one :bike
    has_one :car

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_action :authenticate_user!

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController

  before_action :find_bikes, only:[:show, :edit, :update, :destroy]

  def index
    @bikes = Bike.all.order("name ASC")
  end

  def new
    @bike = Bike.new
    @manufacturers = Manufacturer.all.map{ |c| [c.name, c.id]}
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.manufacturer_id = params[:manufacturer_id]
      if @bike.save
        redirect_to root_path
      else
        render 'new'
    end
  end

  def show

  end


    def update
    @bike.manufacturer_id = params[:manufacturer_id]
    if @bike.update(bike_params)
      redirect_to bike_path(@bike)
    else
      render 'edit'
    end
  end


  def edit
    @manufacturers = Manufacturer.all.map{ |c| [c.name, c.id] }
    @modells = Modell.all.map{ |m| [m.name, m.id] }
    @bodies = Body.all.map{ |b| [b.name, b.id] }
    @engines = Engine.all.map{ |e| [e.name, e.id]}
    @fuels = Fuel.all.map{ |f| [f.name, f.id]}
    @fuel_efficiencies = FuelEfficiency.all.map{ |g| [g.mpg, g.id]}
  end


  def destroy
    @bike.destroy
      redirect_to root_path
  end

  private

  def bike_params
    params.require(:bike).permit(:name, :description, :manufacturer_id, :date, :meta_title, :meta_description, :permalink, :no_index)
  end

  def find_bikes
    @bike = Bike.find(params[:id])
  end

end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/modells_helper.rb
module ModellsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/speeds_helper.rb
module SpeedsHelper
end

app/views/bikes/_form.html.erb
<h1>Form Bike Page</h1>

<%= simple_form_for @bike, :html => { :multipart => true } do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :date, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 12, discard_day: true, order: [:month, :year] %>
  <%= select_tag(:manufacturer_id, options_for_select(@manufacturers), :prompt => "Select Manufacturer") %></br></br>
  <%= f.button :submit %>

  <%= f.input :no_index, as: :boolean, checked_value: true, unchecked_value: false %>
<% end %>

app/views/bikes/edit.html.erb
<h1>Edit Bike Page</h1>

<%= simple_form_for @bike, :html => { :multipart => true } do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :date, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 12, discard_day: true, order: [:month, :year] %>
  <%= f.select :manufacturer_id, @manufacturers %></br></br>

  <%= f.button :submit %>

  <%= f.input :no_index, as: :boolean, checked_value: true, unchecked_value: false %>
<% end %>

<%= link_to "Back", cars_path %>

app/views/bikes/index.html.erb
<h1>Index Bike Page</h1>

<% @bikes.each do |bike| %>
<h2><%= link_to bike.manufacturer.name + " " + bike.name, bike_path(bike) %></h2>
<% end %>

<%= link_to "Back", root_path %>

app/views/bikes/new.html.erb
<h1>New Bike Page</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/bikes/show.html.erb
<h1>Show Bike Page</h1>

<h4><%= @bike.manufacturer.name %></h4>
<h4><%= @bike.name %></h4>
<h4><%= @bike.description %></h4>
<h4><%= @bike.date %></h4>

<%= link_to "Back", bikes_path %>
<%= link_to "Edit", edit_bike_path(@bike) %>
<%= link_to "Delete", bike_path(@bike), method: :delete, data: {confirm: "Are you sure?"} %>