config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/history'

  get 'pages/how'

  get 'pages/terms'

resources :manufacturers, :cars, :bikes, :modells, :bodies, :engines, :fuels, :fuel_efficiencies, :speeds, :prices
  root "pages#home"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord

  belongs_to :manufacturer
  belongs_to :body
  belongs_to :modell
  belongs_to :engine
  belongs_to :fuel

end

app/models/body.rb
class Body < ApplicationRecord

  has_one :car
  has_one :bike
end

app/models/car.rb
class Car < ApplicationRecord

  belongs_to :manufacturer
  belongs_to :modell
  belongs_to :body
  belongs_to :engine
  belongs_to :fuel
  belongs_to :fuel_efficiency
  belongs_to :speed

end

app/models/engine.rb
class Engine < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/fuel.rb
class Fuel < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/fuel_efficiency.rb
class FuelEfficiency < ApplicationRecord

  has_one :car
  has_one :bike

end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord

  has_many :cars
  has_many :bikes
  has_many :modells
  has_many :bodies

end

app/models/modell.rb
class Modell < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/price.rb
class Price < ApplicationRecord

  has_one :bike
  has_one :car

end

app/models/speed.rb
class Speed < ApplicationRecord

    has_one :bike
    has_one :car

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_action :authenticate_user!

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/modells_controller.rb
class ModellsController < ApplicationController

  before_action :find_modell, only:[:show, :edit, :update, :destroy]

  def index
    @modells = Modell.all.order("name ASC")
  end

  def new
    @modell = Modell.new
    @manufacturers = Manufacturer.all.map{ |c| [c.name, c.id] }
  end

  def create
    @modell = Modell.new(modell_params)
    @modell.manufacturer_id = params[:manufacturer_id]
      if @modell.save
        redirect_to root_path
      else
        render 'new'
    end
  end

  def show

  end

  def edit
    @modells = Modell.all.map{ |c| [c.name, c.id] }
    @manufacturers = Manufacturer.all.map{ |c| [c.name, c.id] }
  end

  def update
    if @modell.update(modell_params)
      redirect_to modell_path(@modell)
    else
      render 'edit'
    end
  end

  def destroy
    @modell.destroy
      redirect_to root_path
  end

  private

  def modell_params
    params.require(:modell).permit(:name, :description, :manufacturer_id, :date, :meta_title, :meta_description, :permalink, :no_index)
  end

  def find_modell
    @modell = Modell.find(params[:id])
  end

end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/modells_helper.rb
module ModellsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/speeds_helper.rb
module SpeedsHelper
end

app/views/modells/_form.html.erb
<h1>Form Modell Page</h1>

<%= simple_form_for @modell, :html => { :multipart => true } do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :date, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 12, discard_day: true, order: [:month, :year] %>
  <%= select_tag(:manufacturer_id, options_for_select(@manufacturers), :prompt => "Select Manufacturer") %></br></br>
  <%= f.button :submit %>

  <%= f.input :no_index, as: :boolean, checked_value: true, unchecked_value: false %>
<% end %>

app/views/modells/edit.html.erb
<h1>Edit Modell Page</h1>

<%= simple_form_for @modell, :html => { :multipart => true } do |f| %></br></br>

  <%= f.input :name %></br></br>

  <%= f.input :description, as: :text %></br></br>

  <%= f.input :date, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 12, discard_day: true, order: [:month, :year] %></br></br>

  <%= f.select :manufacturer_id, @manufacturers %></br></br>

  <%= f.input :no_index, as: :boolean, checked_value: true, unchecked_value: false %></br></br>

  <%= f.button :submit %></br></br>


<% end %>

<%= link_to "Back", cars_path %>

app/views/modells/index.html.erb
<h1>Index Modell Page</h1>

<% @modells.each do |modell| %>
<h2><%= link_to modell.manufacturer.name + " " + modell.name, modell_path(modell) %></h2>
<% end %>

<%= link_to "Back", root_path %>

app/views/modells/new.html.erb
<h1>New Modell Page</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/modells/show.html.erb
<h1>Show Modell Page</h1>

<h4><%= @modell.manufacturer.name %></h4>
<h2><%= @modell.name %></h2>
<h2><%= @modell.description %></h2>
<h2><%= @modell.date %></h2>



<%= link_to "Back", modells_path %>
<%= link_to "Edit", edit_modell_path(@modell) %>
<%= link_to "Delete", modell_path(@modell), method: :delete, data: {confirm: "Are you sure?"} %>