config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/history'

  get 'pages/how'

  get 'pages/terms'

resources :manufacturers, :cars, :bikes, :modells, :bodies, :engines, :fuels, :fuel_efficiencies, :speeds, :prices
  root "pages#home"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/bike.rb
class Bike < ApplicationRecord

  belongs_to :manufacturer
  belongs_to :body
  belongs_to :modell
  belongs_to :engine
  belongs_to :fuel

end

app/models/body.rb
class Body < ApplicationRecord

  has_one :car
  has_one :bike
end

app/models/car.rb
class Car < ApplicationRecord

  belongs_to :manufacturer
  belongs_to :modell
  belongs_to :body
  belongs_to :engine
  belongs_to :fuel
  belongs_to :fuel_efficiency
  belongs_to :speed

end

app/models/engine.rb
class Engine < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/fuel.rb
class Fuel < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/fuel_efficiency.rb
class FuelEfficiency < ApplicationRecord

  has_one :car
  has_one :bike

end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord

  has_many :cars
  has_many :bikes
  has_many :modells
  has_many :bodies

end

app/models/modell.rb
class Modell < ApplicationRecord

  belongs_to :manufacturer
  has_one :car
  has_one :bike

end

app/models/price.rb
class Price < ApplicationRecord

  has_one :bike
  has_one :car

end

app/models/speed.rb
class Speed < ApplicationRecord

    has_one :bike
    has_one :car

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_action :authenticate_user!

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/fuel_efficiencies_controller.rb
class FuelEfficienciesController < ApplicationController

  before_action :find_fuel_efficiency, only:[:show, :edit, :update, :destroy]

  def index
    @fuel_efficiencies = FuelEfficiency.all.order("mpg ASC")
  end

  def new
    @fuel_efficiency = FuelEfficiency.new
  end

  def create
    @fuel_efficiency = FuelEfficiency.new(fuel_efficiency_params)
    if @fuel_efficiency.save
      redirect_to root_path
    else
      render 'new'
    end
  end


  def show

  end

  def edit
    @fuel_efficiencies = FuelEfficiency.all.map{ |e| [e.mpg, e.id]}
    @manufacturers = Manufacturer.all.map{ |c| [c.name, c.id] }
  end


  def update
    if @fuel_efficiency.update(fuel_efficiency_params)
      redirect_to fuel_efficiency_path(@fuel_efficiency)
    else
      render 'edit'
    end
  end

  def destroy
    @fuel_efficiency.destroy
      redirect_to root_path
  end

  private

  def fuel_efficiency_params
    params.require(:fuel_efficiency).permit(:mpg, :kml, :meta_title, :meta_description, :permalink, :no_index)
  end

  def find_fuel_efficiency
    @fuel_efficiency = FuelEfficiency.find(params[:id])
  end

end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/helpers/fuel_efficiencies_helper.rb
module FuelEfficienciesHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/modells_helper.rb
module ModellsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/speeds_helper.rb
module SpeedsHelper
end

app/views/fuel_efficiencies/_form.html.erb
<h2>Fuel Efficiency Form</h2>


<%= simple_form_for @fuel_efficiency, :html => { :multipart => true } do |f| %></br></br>

  <%= f.input :mpg %></br></br>
  <%= f.input :kml %></br></br>


  <%= f.input :no_index, as: :boolean, checked_value: true, unchecked_value: false %></br></br>

  <%= f.button :submit %></br></br>

<% end %>

<%= link_to "Back", root_path %>

app/views/fuel_efficiencies/edit.html.erb
<h2>Fuel Efficiency Edit</h2>

<%= simple_form_for @fuel_efficiency, :html => { :multipart => true } do |f| %></br></br>

  <%= f.input :mpg %></br></br>
  <%= f.input :kml %></br></br>

  <%= f.input :no_index, as: :boolean, checked_value: true, unchecked_value: false %></br></br>

  <%= f.button :submit %></br></br>

<% end %>

<%= link_to "Back", root_path %>

app/views/fuel_efficiencies/index.html.erb
<h2>Fuel Efficiency Index</h2>

<% @fuel_efficiencies.each do |fuel_efficiency| %>
<h2><%= link_to fuel_efficiency.mpg, fuel_efficiency_path(fuel_efficiency) %></h2>
<% end %>

<%= link_to "Back", root_path %>

app/views/fuel_efficiencies/new.html.erb
<h2>Fuel Efficiency New</h2>

<%= render 'form' %>

app/views/fuel_efficiencies/show.html.erb
<h2>Fuel Efficiency Show</h2>


<h4><%= @fuel_efficiency.mpg %></h4>
<h4><%= @fuel_efficiency.kml %></h4>

<%= link_to "Back", fuel_efficiencies_path %>
<%= link_to "Edit", edit_fuel_efficiency_path(@fuel_efficiency) %>
<%= link_to "Delete", fuel_efficiency_path(@fuel_efficiency), method: :delete, data:{confirm: "Are you sure?"} %>